# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccflow < Formula
  desc "CLI tool for creating and managing Claude Code workflows"
  homepage "https://github.com/Wameedh/ccflow"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Wameedh/ccflow/releases/download/v0.5.0/ccflow_0.5.0_darwin_amd64.tar.gz"
      sha256 "dcbb60d009d474f5fb13e670a53669d050b496d1fedb58eed6a2f3c71099c6d7"

      def install
        bin.install "ccflow"
      end
    end
    on_arm do
      url "https://github.com/Wameedh/ccflow/releases/download/v0.5.0/ccflow_0.5.0_darwin_arm64.tar.gz"
      sha256 "e2c586ba6ccae9a1e7b2c20c17050433165969c0d13475481f30fc98c5a04244"

      def install
        bin.install "ccflow"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Wameedh/ccflow/releases/download/v0.5.0/ccflow_0.5.0_linux_amd64.tar.gz"
        sha256 "f0a93f25ab3436cde85bddefd49690d96336a8ca86c4cc3188b7ed933abedf19"

        def install
          bin.install "ccflow"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Wameedh/ccflow/releases/download/v0.5.0/ccflow_0.5.0_linux_arm64.tar.gz"
        sha256 "fec883c5e0da1737caa5bacd4700614adbf57ff221136ea2be0ed54ba6f5e556"

        def install
          bin.install "ccflow"
        end
      end
    end
  end

  test do
    system "#{bin}/ccflow", "version"
  end
end
