# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccflow < Formula
  desc "CLI tool for creating and managing Claude Code workflows"
  homepage "https://github.com/Wameedh/ccflow"
  version "0.6.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Wameedh/ccflow/releases/download/v0.6.1/ccflow_0.6.1_darwin_amd64.tar.gz"
      sha256 "d68b98d386fc0aa63e5143fe9883d5d92376f39d430923e179f1146f6c4730c7"

      def install
        bin.install "ccflow"
      end
    end
    on_arm do
      url "https://github.com/Wameedh/ccflow/releases/download/v0.6.1/ccflow_0.6.1_darwin_arm64.tar.gz"
      sha256 "e271689449167d741dc84b247c97f0030a376868c36b4d04954191aebb788338"

      def install
        bin.install "ccflow"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Wameedh/ccflow/releases/download/v0.6.1/ccflow_0.6.1_linux_amd64.tar.gz"
        sha256 "5e667a34f662c1fb267e5a98968e66da332aceb1df28816c5a0535411c7b9425"

        def install
          bin.install "ccflow"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Wameedh/ccflow/releases/download/v0.6.1/ccflow_0.6.1_linux_arm64.tar.gz"
        sha256 "0e8c83743b51c9b6edb1fc208bb816543774781da19cbb267cbab91cf895b30e"

        def install
          bin.install "ccflow"
        end
      end
    end
  end

  test do
    system "#{bin}/ccflow", "version"
  end
end
