# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccflow < Formula
  desc "CLI tool for creating and managing Claude Code workflows"
  homepage "https://github.com/Wameedh/ccflow"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Wameedh/ccflow/releases/download/v0.3.0/ccflow_0.3.0_darwin_amd64.tar.gz"
      sha256 "70073a9614f731dace816aea5010e03507be2bb6431ada10a70b899e888bc06c"

      def install
        bin.install "ccflow"
      end
    end
    on_arm do
      url "https://github.com/Wameedh/ccflow/releases/download/v0.3.0/ccflow_0.3.0_darwin_arm64.tar.gz"
      sha256 "1a28e6b9c3e7d6acc0bd84f5662eda3abc234916a5ec94b2039876fe685a2e87"

      def install
        bin.install "ccflow"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Wameedh/ccflow/releases/download/v0.3.0/ccflow_0.3.0_linux_amd64.tar.gz"
        sha256 "ebb340cc9fab8df316e196b1ca0676a238a9bc984c2870486f1971377b082135"

        def install
          bin.install "ccflow"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Wameedh/ccflow/releases/download/v0.3.0/ccflow_0.3.0_linux_arm64.tar.gz"
        sha256 "2461bb24b61042c2cf952ffcf0083d00c62c80cb0040c960095f61e7813472a9"

        def install
          bin.install "ccflow"
        end
      end
    end
  end

  test do
    system "#{bin}/ccflow", "version"
  end
end
